name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Check
      run: cargo c --verbose
    - name: Clippy
      run: cargo clippy
    - name: Build
      run: cargo b --verbose
    - name: Run tests
      run: cargo t --verbose
